### ISSUE TITLE
Invalid reference format: repository name must be lowercase

### ISSUE THREAD

**Issue by zedy-wj** [bradygaster/RockPaperOrleans#11]
**Describe the issue:**
When executing the `azd package` command, building service 'gamecontroller' needs your repository name must be lowercase.
![image](https://user-images.githubusercontent.com/81678720/229775845-51cbedc5-3ffd-4991-9f07-5578711e1030.png)

**Repro Steps:**

1. azd init -t <template_name>
2. azd package

**Environment:**
OS: Windows
Azd version: azd version 0.7.0-beta.2-pr.2672227 (commit dec4eb2c9f5932d3bd41f7e66b41c775c050ad48)

**Expected behavior:**
Execute the azd package command can pass.

@rajeshkamal5050, @bradygaster  for notification.

**Comment by bradygaster** [comment]
That would mean every repository that would ever need to use AZD would also need to change. I think changing AZD would be much simpler. I'll make sure to relay this to the AZD team.
